/**
 * DApiGate
 * DApiGate `Reaper API` documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IpGetResponseDTO {
	/**
	 * IP country code
	 */
	country?: null | string;
	/**
	 * IP currency
	 */
	currency?: string;
	/**
	 * IP address
	 */
	ip?: string;
}
