/**
 * DApiGate
 * DApiGate `Reaper API` documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PhoneGetResponseDTO {
	/**
	 * Phone carrier
	 */
	carrier?: null | string;
	/**
	 * Proxy code
	 */
	country?: null | string;
	/**
	 * Phone valid status
	 */
	isValid?: boolean;
	/**
	 * Phone wallet number
	 */
	phone?: number;
}
