/**
 * DApiGate
 * DApiGate `Reaper API` documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ProxyGetResponseDTO } from "./proxy-get-response-dto.model";

export interface ProxyGetListResponseDTO {
	/**
	 * ProxyGetResponseDTO Total number of items on page
	 */
	count?: number;
	/**
	 * ProxyGetResponseDTO Current page number
	 */
	currentPage?: number;
	/**
	 * Array of ProxyGetResponseDTO
	 */
	items?: Set<ProxyGetResponseDTO>;
	/**
	 * ProxyGetResponseDTO Total number of items
	 */
	totalCount?: number;
	/**
	 * ProxyGetResponseDTO Total number of pages
	 */
	totalPages?: number;
}
