/**
 * DApiGate
 * DApiGate `Reaper API` documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProxyGetResponseDTO {
	/**
	 * Proxy code
	 */
	country?: string;
	/**
	 * Proxy IP
	 */
	ip?: string;
	/**
	 * Proxy password
	 */
	password?: string;
	/**
	 * Proxy port
	 */
	port?: number;
	/**
	 * Proxy login
	 */
	username?: string;
}
