/**
 * DApiGate
 * DApiGate `Reaper API` documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UnauthorizedResponseDTO {
	/**
	 * Correlation identifier
	 */
	correlationID?: string;
	/**
	 * Error name
	 */
	error?: string;
	/**
	 * Error message
	 */
	message?: string;
	/**
	 * Error status code
	 */
	statusCode?: UnauthorizedResponseDTO.StatusCodeEnum;
	/**
	 * Error timestamp
	 */
	timestamp?: number;
}
export namespace UnauthorizedResponseDTO {
	export type StatusCodeEnum = 100 | 101 | 102 | 103 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226 | 300 | 301 | 302 | 303 | 304 | 305 | 306 | 307 | 308 | 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 421 | 422 | 423 | 424 | 425 | 426 | 428 | 429 | 431 | 451 | 500 | 501 | 502 | 503 | 504 | 505 | 506 | 507 | 508 | 510 | 511;
	export const StatusCodeEnum = {
		NUMBER_100: 100 as StatusCodeEnum,
		NUMBER_101: 101 as StatusCodeEnum,
		NUMBER_102: 102 as StatusCodeEnum,
		NUMBER_103: 103 as StatusCodeEnum,
		NUMBER_200: 200 as StatusCodeEnum,
		NUMBER_201: 201 as StatusCodeEnum,
		NUMBER_202: 202 as StatusCodeEnum,
		NUMBER_203: 203 as StatusCodeEnum,
		NUMBER_204: 204 as StatusCodeEnum,
		NUMBER_205: 205 as StatusCodeEnum,
		NUMBER_206: 206 as StatusCodeEnum,
		NUMBER_207: 207 as StatusCodeEnum,
		NUMBER_208: 208 as StatusCodeEnum,
		NUMBER_226: 226 as StatusCodeEnum,
		NUMBER_300: 300 as StatusCodeEnum,
		NUMBER_301: 301 as StatusCodeEnum,
		NUMBER_302: 302 as StatusCodeEnum,
		NUMBER_303: 303 as StatusCodeEnum,
		NUMBER_304: 304 as StatusCodeEnum,
		NUMBER_305: 305 as StatusCodeEnum,
		NUMBER_306: 306 as StatusCodeEnum,
		NUMBER_307: 307 as StatusCodeEnum,
		NUMBER_308: 308 as StatusCodeEnum,
		NUMBER_400: 400 as StatusCodeEnum,
		NUMBER_401: 401 as StatusCodeEnum,
		NUMBER_402: 402 as StatusCodeEnum,
		NUMBER_403: 403 as StatusCodeEnum,
		NUMBER_404: 404 as StatusCodeEnum,
		NUMBER_405: 405 as StatusCodeEnum,
		NUMBER_406: 406 as StatusCodeEnum,
		NUMBER_407: 407 as StatusCodeEnum,
		NUMBER_408: 408 as StatusCodeEnum,
		NUMBER_409: 409 as StatusCodeEnum,
		NUMBER_410: 410 as StatusCodeEnum,
		NUMBER_411: 411 as StatusCodeEnum,
		NUMBER_412: 412 as StatusCodeEnum,
		NUMBER_413: 413 as StatusCodeEnum,
		NUMBER_414: 414 as StatusCodeEnum,
		NUMBER_415: 415 as StatusCodeEnum,
		NUMBER_416: 416 as StatusCodeEnum,
		NUMBER_417: 417 as StatusCodeEnum,
		NUMBER_418: 418 as StatusCodeEnum,
		NUMBER_421: 421 as StatusCodeEnum,
		NUMBER_422: 422 as StatusCodeEnum,
		NUMBER_423: 423 as StatusCodeEnum,
		NUMBER_424: 424 as StatusCodeEnum,
		NUMBER_425: 425 as StatusCodeEnum,
		NUMBER_426: 426 as StatusCodeEnum,
		NUMBER_428: 428 as StatusCodeEnum,
		NUMBER_429: 429 as StatusCodeEnum,
		NUMBER_431: 431 as StatusCodeEnum,
		NUMBER_451: 451 as StatusCodeEnum,
		NUMBER_500: 500 as StatusCodeEnum,
		NUMBER_501: 501 as StatusCodeEnum,
		NUMBER_502: 502 as StatusCodeEnum,
		NUMBER_503: 503 as StatusCodeEnum,
		NUMBER_504: 504 as StatusCodeEnum,
		NUMBER_505: 505 as StatusCodeEnum,
		NUMBER_506: 506 as StatusCodeEnum,
		NUMBER_507: 507 as StatusCodeEnum,
		NUMBER_508: 508 as StatusCodeEnum,
		NUMBER_510: 510 as StatusCodeEnum,
		NUMBER_511: 511 as StatusCodeEnum,
	};
}
